/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#define RCC_BASE 	0x40021000
#define GPIOA_BASE  0x40010800
#define RCC_APB2ENR *(volatile unsigned int *)(RCC_BASE+0x18)
#define GPIOA_CRH 	*(volatile unsigned int *)(GPIOA_BASE+0x04)
#define GPIOA_ODR	*(volatile unsigned int *)(GPIOA_BASE+0x0C)
typedef union{
	volatile unsigned int all_fields;
	struct{
		volatile unsigned int reserved:13;
		volatile unsigned int P_13:1;
	}pin;
}R_ODR_t;


#include <stdint.h>
int main(void)
{
    volatile R_ODR_t* R_ODR=(volatile R_ODR_t*) (GPIOA_BASE+0x0C);
    int i;
	RCC_APB2ENR |=(1<<2);
    GPIOA_CRH &=0xFF0FFFFF;
    GPIOA_CRH |=0x00200000;
    while(1){
    	R_ODR->pin.P_13=1;
    	for(i=0;i<50000;i++);
    	R_ODR->pin.P_13=0;
    	for(i=0;i<50000;i++);




    }
    return 0;
}
