/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#define RCC_BASE 	0x40021000
#define RCC_APB2ENR	*(volatile unsigned int *)(RCC_BASE+0x18)

#define GPIOA_BASE  0x40010800
#define GPIOA_CRH 	*(volatile unsigned int *)(GPIOA_BASE+0x04)
#define GPIOA_CRL 	*(volatile unsigned int *)(GPIOA_BASE+0x00)
#define GPIOA_ODR	*(volatile unsigned int *)(GPIOA_BASE+0x0C)
#define EXTI_BASE	0x40010400
#define EXTI_IMR	*(volatile unsigned int *)(EXTI_BASE+0x00)
#define EXTI_RTSR	*(volatile unsigned int *)(EXTI_BASE+0x08)
#define EXTI_PR	*(volatile unsigned int *)(EXTI_BASE+0x014)



#define  NVIC_ISER0	*(volatile unsigned int *)(0xE000E100)

#define AFIO_BASE		0x40010000
#define AFIO_EXTICR1	*(volatile unsigned int *)(AFIO_BASE+0x08)

void clock_init(void);
void GPIO_init(void);


#include <stdint.h>
int main(void)
{
    clock_init();
    GPIO_init();
    AFIO_EXTICR1=0;
    EXTI_RTSR |=(1<<0);
    EXTI_IMR |=(1<<0);
    NVIC_ISER0 |=(1<<6);
    while(1);
    return 0;
}
void clock_init(void){
	 //APB2 peripheral clock enable register to enable GPIO
		RCC_APB2ENR |=(1<<2);
		// Bit 0 AFIOEN: Alternate function IO clock enable
		RCC_APB2ENR |= (1>>0);
}
void GPIO_init(void){
	GPIOA_CRH &=0xFF0FFFFF;
	GPIOA_CRH |=0x00200000;
	GPIOA_CRL |=(1<<2);

}
void EXTI0_IRQHandler(void){
	GPIOA_ODR ^=(1<<13);
	EXTI_PR |=(1<<0);
}
